// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            string
	Name          string
	Url           string
	UserID        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        string
	UserID    string
	FeedID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      sql.NullString
}
